[package]
name = "surfaces_comparison"
version = "0.1.1"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "surfaces_comparison"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
rayon = "1.7.0"